// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// BhattacharyyaDist_rcpp
NumericMatrix BhattacharyyaDist_rcpp(CharacterMatrix x, double offset);
RcppExport SEXP _DiscreteGapStatistic_BhattacharyyaDist_rcpp(SEXP xSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(BhattacharyyaDist_rcpp(x, offset));
    return rcpp_result_gen;
END_RCPP
}
// ChisqDist_rcpp
NumericMatrix ChisqDist_rcpp(CharacterMatrix x);
RcppExport SEXP _DiscreteGapStatistic_ChisqDist_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ChisqDist_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DiscreteGapStatistic_BhattacharyyaDist_rcpp", (DL_FUNC) &_DiscreteGapStatistic_BhattacharyyaDist_rcpp, 2},
    {"_DiscreteGapStatistic_ChisqDist_rcpp", (DL_FUNC) &_DiscreteGapStatistic_ChisqDist_rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DiscreteGapStatistic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
