# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bhattacharyya Distance
#'
#' @name BhattacharyyaDist_rcpp
#' @title Bhattacharyya Distance via Rcpp
#' @description Computes pairwise Bhattacharyya distance between rows.
#' @param x n X p character matrix.
#' @param offset small offset for log(0*0) cases.
#' @return Distance matrix between rows.
#' @export
NULL

#' Chi-square Distance
#'
#' @name ChisqDist_rcpp
#' @title Chi-square Distance via Rcpp
#' @description Computes pairwise Chi-square distance between rows.
#' @param x n X p character matrix.
#' @return Distance matrix between rows.
#' @export
NULL

BhattacharyyaDist_rcpp <- function(x, offset = 1e-8) {
    .Call(`_DiscreteGapStatistic_BhattacharyyaDist_rcpp`, x, offset)
}

ChisqDist_rcpp <- function(x) {
    .Call(`_DiscreteGapStatistic_ChisqDist_rcpp`, x)
}

